title: My first blog
author: protondrive
email: molecularmachinist@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A github bot helps me create my first blog.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  protondrive # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
